// Define global variables
def registry = 'https://satishk.jfrog.io'
def imageName = 'satishk.jfrog.io/satish-docker-local/sample_app'
def version   = '2.1.2'
def projectFolder = 'DevOps Project-04'  // <-- folder Maven project (pom.xml ada di sini)

pipeline {
    agent {
        node {
            label 'maven'
        }
    }
    environment {
        PATH = "/opt/apache-maven-3.9.4/bin:$PATH"
    }

    stages {

        stage("Debug Workspace") {
            steps {
                echo "----------- Debug Workspace ----------"
                sh 'pwd'
                sh 'ls -R'
                echo "-------------------------------------"
            }
        }

        stage("Build") {
            steps {
                echo "----------- Build Started ----------"
                dir(projectFolder) {
                    sh 'mvn clean deploy -Dmaven.test.skip=true'
                }
                echo "----------- Build Completed ----------"
            }
        }

        stage("Unit Test") {
            steps {
                echo "----------- Unit Test Started ----------"
                dir(projectFolder) {
                    sh 'mvn surefire-report:report'
                }
                echo "----------- Unit Test Completed ----------"
            }
        }

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'satish-sonarqube-scanner'
            }
            steps {
                withSonarQubeEnv('satish-sonarqube-server') {
                    sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectBaseDir=${projectFolder}"
                }
            }
        }

        stage("Quality Gate") {
            steps {
                script {
                    timeout(time: 1, unit: 'HOURS') {
                        def qg = waitForQualityGate()
                        if (qg.status != 'OK') {
                            error "Pipeline aborted due to quality gate failure: ${qg.status}"
                        }
                    }
                }
            }
        }

        stage("Jar Publish") {
            steps {
                script {
                    echo '<--------------- Jar Publish Started --------------->'
                    def server = Artifactory.newServer(
                        url: registry + "/artifactory",
                        credentialsId: "jfrog_cred"
                    )
                    def properties = "buildid=${env.BUILD_ID},commitid=${GIT_COMMIT}"
                    def uploadSpec = """{
                        "files": [
                            {
                                "pattern": "${projectFolder}/target/*.jar",
                                "target": "maven-libs-release-local/",
                                "flat": "true",
                                "props": "${properties}",
                                "exclusions": ["*.sha1", "*.md5"]
                            }
                        ]
                    }"""
                    def buildInfo = server.upload(uploadSpec)
                    buildInfo.env.collect()
                    server.publishBuildInfo(buildInfo)
                    echo '<--------------- Jar Publish Ended --------------->'
                }
            }
        }

        stage("Docker Build") {
            steps {
                script {
                    echo '<--------------- Docker Build Started --------------->'
                    dir(projectFolder) {
                        app = docker.build("${imageName}:${version}")
                    }
                    echo '<--------------- Docker Build Ended --------------->'
                }
            }
        }

        stage("Docker Publish") {
            steps {
                script {
                    echo '<--------------- Docker Publish Started --------------->'
                    docker.withRegistry(registry, 'jfrog_cred') {
                        app.push()
                    }
                    echo '<--------------- Docker Publish Ended --------------->'
                }
            }
        }

        stage("Helm Deploy") {
            steps {
                script {
                    echo '<--------------- Helm Deploy Started --------------->'
                    sh 'helm install sample-app sample-app-1.0.1 || helm upgrade sample-app sample-app-1.0.1'
                    echo '<--------------- Helm Deploy Ended --------------->'
                }
            }
        }

    }
}
