// ================= GLOBAL VARIABLES =================
def registry = 'https://trialex7xj8.jfrog.io'
def imageName = 'trialex7xj8.jfrog.io/docker-trial/sample_app'
def version       = '2.1.2'
def projectFolder = 'DevOps Project-04'   // folder pom.xml
def app

pipeline {
    agent {
        node {
            label 'maven'
        }
    }

    environment {
        PATH = "/opt/apache-maven-3.9.4/bin:$PATH"
    }

    stages {

        // ================= CHECKOUT =================
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        // ================= DEBUG =================
        stage('Debug Workspace') {
            steps {
                sh '''
                echo "===== WORKSPACE ====="
                pwd
                ls -lah
                '''
            }
        }

        // ================= BUILD =================
        stage('Build') {
            steps {
                dir(projectFolder) {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        // ================= UNIT TEST =================
        stage('Unit Test') {
            steps {
                echo 'Unit test dilewati (VM low resource)'
            }
        }

        // ================= SONARCLOUD =================
        stage('SonarCloud Analysis') {
            steps {
                dir(projectFolder) {
                    withSonarQubeEnv('SonarCloud') {
                        sh '''
                        mvn sonar:sonar \
                          -Dsonar.projectKey=destiaeka_DevOps-Projects \
                          -Dsonar.organization=destiaeka \
                          -Dsonar.host.url=https://sonarcloud.io
                        '''
                    }
                }
            }
        }


        // ================ UPLOAD ARTIFACT =============
        stage('Upload Artifact to Artifactory') {
            steps {
                dir('DevOps Project-04') {
                    rtUpload (
                        serverId: 'artifactory-server',
                        spec: """{
                          "files": [
                            {
                              "pattern": "target/*.jar",
                              "target": "demo-repo/"
                            }
                          ]
                        }"""
                    )
                }
            }
        }

        // ================= JAR PUBLISH =================
        stage('Jar Publish') {
            steps {
                script {
                    echo 'Publishing JAR to Artifactory'

                    // gunakan credentials Jenkins
                    def server = Artifactory.newServer(
                        url: "${registry}/artifactory",
                        credentialsId: "jfrog_cred"
                    )

                    def uploadSpec = """{
                      "files": [
                        {
                          "pattern": "${projectFolder}/target/*.jar",
                          "target": "tf-trial/",
                          "flat": "true"
                        }
                      ]
                    }"""

                    def buildInfo = server.upload(uploadSpec)
                    server.publishBuildInfo(buildInfo)

                    echo "JAR uploaded to Artifactory"
                }
            }
        }

        // ================= DOCKER BUILD =================
        stage('Docker Build') {
            steps {
                script {
                    echo 'Docker Build'
                    dir(projectFolder) {
                        app = docker.build("${imageName}:${version}")
                    }
                }
            }
        }

        // ================= DOCKER PUSH =================
        stage('Docker Publish') {
            steps {
                script {
                    echo 'Docker Push to Artifactory Registry'

                    docker.withRegistry(registry, 'jfrog_cred') {
                        app.push(version)
                    }
                }
            }
        }

        // ================= HELM DEPLOY =================
        stage('Helm Deploy') {
            steps {
                echo 'Helm Deploy'
                sh '''
                helm upgrade --install sample-app sample-app-1.0.1
                '''
            }
        }
    }

    // ================= POST ACTION =================
    post {
        success {
            echo 'Pipeline SUCCESS'
        }
        failure {
            echo 'Pipeline FAILED'
        }
    }
}
