pipeline {
    agent any

    tools {
        jdk 'jdk17'
    }
    
    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }

    stages {
        stage('clean workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout From Git') {
            steps {
                git branch: 'main', url: 'https://github.com/destiaeka/DevOps-Projects.git'
            }
        }

        stage("Sonarqube Analysis") {
            steps {
                dir('DevOps-Project-11/DotNet-monitoring') {
                    withSonarQubeEnv('sonar-server') {
                        sh """$SCANNER_HOME/bin/sonar-scanner \
                        -Dsonar.projectName=Dotnet-Webapp \
                        -Dsonar.projectKey=Dotnet-Webapp"""
                    }
                }
            }
        }

        stage("quality gate") {
            steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'Sonar-token'
                }
            }
        }

        stage("TRIVY File scan") {
            steps {
                dir('DevOps-Projects/DevOps-Project-11/DotNet-monitoring') {
                    sh "trivy fs . > trivy-fs_report.txt"
                }
            }
        }
        
        stage("Docker Build & tag"){
            steps{
                dir('DevOps-Project-11/DotNet-monitoring') {
                    script{
                        withDockerRegistry(credentialsId: 'docker', toolName: 'docker'){   
                            sh """docker build . --file build/Dockerfile --tag docker.io/destiaeka/dotnet-monitoring:latest"""
                        }
                    }
                }
            }
        }
        
        stage("TRIVY"){
            steps{
                dir('DevOps-Project-11/DotNet-monitoring') {
                    sh "trivy image destiaeka/dotnet-monitoring:latest > trivy.txt"
                }
            }
        }
        
        stage("Docker Push"){
            steps{
                dir('DevOps-Project-11/DotNet-monitoring') {
                    script{
                        withDockerRegistry(credentialsId: 'docker', toolName: 'docker'){   
                            sh "docker push docker.io/destiaeka/dotnet-monitoring:latest"
                        }
                    }
                }
            }
        }
        stage("Deploy to container"){
            steps{
                sh "docker run -d --name dotnet -p 5000:5000 destiaeka/dotnet-monitoring:latest"
            } 
        }
        
        stage('Deploy to k8s'){
            steps{
                dir('DevOps-Project-11/DotNet-monitoring/K8S') {
                    withKubeConfig(
                        credentialsId: 'k8s'
                    ) {
                        sh 'kubectl apply -f deployment.yaml'
                    }
                }   
            }
        }
    }
}