apiVersion: v1
kind: Pod
metadata:
  name: tictactoe-pod
  labels:
    app: myapp
spec:
  containers:
  - name: tictactoe-pod
    image: destiaeka/tictactoe
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: tictactoe-service
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 80